export const translations = {
    en: {
        nav_services: 'Services',
        nav_about: 'About Us',
        nav_why_us: 'Why Choose Us',
        nav_contact: 'Contact',
        hero_title: 'Connecting Continents, Delivering Trust',
        hero_subtitle: 'Your premier partner in global logistics and export solutions. Fast, reliable, and efficient.',
        hero_cta: 'Get a Free Quote',
        services_title: 'Our Core Services',
        service_ocean_title: 'Ocean Freight',
        service_ocean_desc: 'Comprehensive sea freight services for full container loads (FCL) or less-than-container loads (LCL).',
        service_air_title: 'Air Freight',
        service_air_desc: 'Expedited air freight solutions for time-sensitive shipments, connecting you to major global hubs.',
        service_warehouse_title: 'Warehousing & Distribution',
        service_warehouse_desc: 'Secure storage and efficient distribution services to streamline your supply chain.',
        about_title: 'Pioneering Global Trade',
        about_desc: 'ExpressDevelop was founded on the principle of making global trade accessible and efficient for businesses of all sizes. With decades of combined experience, our team navigates the complexities of international shipping with precision and care, ensuring your cargo reaches its destination safely and on time.',
        about_cta: 'Learn More',
        why_us_title: 'Technology-Driven Logistics',
        why_us_desc: 'We leverage cutting-edge technology to provide you with real-time tracking, transparent pricing, and streamlined documentation. Our digital platform simplifies the shipping process, giving you complete control and visibility over your supply chain from your desktop or mobile device.',
        why_us_feat1: 'Real-Time Shipment Tracking',
        why_us_feat2: '24/7 Customer Support',
        why_us_feat3: 'Competitive & Transparent Pricing',
        footer_desc: 'Your trusted partner for global transport and export. We deliver excellence, one shipment at a time.',
        footer_links_title: 'Quick Links',
        footer_link_home: 'Home',
        footer_link_services: 'Services',
        footer_link_about: 'About Us',
        footer_link_track: 'Track Shipment',
        footer_link_privacy: 'Privacy Policy',
        footer_contact_title: 'Contact Us',
        footer_follow_title: 'Follow Us',
        footer_copyright: '© 2024 ExpressDevelop. All Rights Reserved.',
    },
    ar: {
        nav_services: 'خدماتنا',
        nav_about: 'من نحن',
        nav_why_us: 'لماذا تختارنا',
        nav_contact: 'اتصل بنا',
        hero_title: 'نصل القارات، ونسلم الثقة',
        hero_subtitle: 'شريكك الأول في حلول اللوجستيات والتصدير العالمية. سريع، موثوق، وفعال.',
        hero_cta: 'احصل على عرض سعر مجاني',
        services_title: 'خدماتنا الأساسية',
        service_ocean_title: 'الشحن البحري',
        service_ocean_desc: 'خدمات شحن بحري شاملة للحاويات الكاملة (FCL) أو الشحنات الجزئية (LCL).',
        service_air_title: 'الشحن الجوي',
        service_air_desc: 'حلول شحن جوي سريعة للشحنات العاجلة، تربطك بأهم المراكز العالمية.',
        service_warehouse_title: 'التخزين والتوزيع',
        service_warehouse_desc: 'خدمات تخزين آمنة وتوزيع فعال لتبسيط سلسلة التوريد الخاصة بك.',
        about_title: 'رواد التجارة العالمية',
        about_desc: 'تأسست ExpressDevelop على مبدأ جعل التجارة العالمية سهلة وفعالة للشركات من جميع الأحجام. بخبرة تمتد لعقود، يتنقل فريقنا في تعقيدات الشحن الدولي بدقة وعناية، مما يضمن وصول بضائعك إلى وجهتها بأمان وفي الوقت المحدد.',
        about_cta: 'اعرف المزيد',
        why_us_title: 'لوجستيات تعتمد على التكنولوجيا',
        why_us_desc: 'نحن نستفيد من أحدث التقنيات لنقدم لك تتبعًا فوريًا وأسعارًا شفافة ووثائق مبسطة. منصتنا الرقمية تبسط عملية الشحن، مما يمنحك تحكمًا ورؤية كاملة على سلسلة التوريد الخاصة بك من جهازك المكتبي أو المحمول.',
        why_us_feat1: 'تتبع الشحنات في الوقت الفعلي',
        why_us_feat2: 'دعم عملاء على مدار الساعة',
        why_us_feat3: 'أسعار تنافسية وشفافة',
        footer_desc: 'شريكك الموثوق للنقل والتصدير العالمي. نقدم التميز، شحنة تلو الأخرى.',
        footer_links_title: 'روابط سريعة',
        footer_link_home: 'الرئيسية',
        footer_link_services: 'خدماتنا',
        footer_link_about: 'من نحن',
        footer_link_track: 'تتبع الشحنة',
        footer_link_privacy: 'سياسة الخصوصية',
        footer_contact_title: 'اتصل بنا',
        footer_follow_title: 'تابعنا',
        footer_copyright: '© 2024 ExpressDevelop. جميع الحقوق محفوظة.',
    }
};